INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (13, 'Notificacion inicial del tema', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a molestie lectus. Maecenas justo metus, ultricies in ligula vitae, semper viverra sem. Pellentesque non facilisis nulla, eu tristique diam. Duis in eros sem. Phasellus eu aliquam odio. Integer elit tellus, convallis non feugiat in, luctus quis erat. Vivamus nunc felis, consequat quis nibh a, suscipit pulvinar sem. Sed quam sapien, vehicula eu sagittis commodo, tincidunt ut tortor. Morbi id nisi sit amet nibh feugiat gravida. Cras odio nisi, accumsan sit amet erat eget, gravida posuere risus. ', 1, 2, 3, 'replied', 14, 1716668647, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (14, 'respuesta a la notificacion inicial', 'Aliquam vitae pulvinar nibh. Etiam in vulputate urna, et mollis odio. Duis risus lorem, fermentum vel lobortis quis, imperdiet nec eros. Duis in justo vestibulum, molestie lectus gravida, ornare enim. Pellentesque vehicula lobortis justo et porta. Quisque sit amet ante in est lobortis ultrices nec a velit. Curabitur faucibus ex quis nibh commodo vehicula. Nulla sagittis nibh at magna facilisis commodo.', 1, 3, 2, 'replied', 15, 1716668721, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (15, 'segunda respuesta', 'sfasdfñshfñsdfhñashdfas', 2, 2, 3, 'read', null, 1716668800, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (16, 'In hac habitasse platea dictumst. Donec vitae dignissim dolor. Phasellus scelerisque mattis diam volutpat semper. Suspendisse consequat rhoncus nunc eget ullamcorper. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', ' Vivamus quis lacus massa. Fusce id felis sed nisl hendrerit placerat. Integer vitae pulvinar odio. Curabitur elementum ligula at orci dapibus, non fermentum quam accumsan. Curabitur sed egestas libero. Mauris non efficitur elit. Praesent semper aliquet justo, quis laoreet justo. Aliquam sit amet felis id metus egestas dignissim. Curabitur eu diam posuere, maximus ipsum in, gravida libero. In commodo nibh in neque facilisis semper. Aliquam non quam ut nulla malesuada iaculis a iaculis tortor.

Aenean sed accumsan mi. Fusce auctor nulla ipsum. Maecenas sollicitudin risus mauris, id interdum augue ultrices et. Nulla pulvinar arcu eu pharetra pulvinar. Suspendisse vitae augue sagittis, aliquet massa nec, molestie ligula. Ut et mi quis purus sagittis efficitur. Donec ornare scelerisque vulputate. Fusce sed velit commodo dolor sagittis mattis. Aenean molestie pretium posuere. Integer tincidunt dolor vitae posuere feugiat. Duis quis felis ante. Curabitur vel dui eget justo commodo dignissim. Phasellus porta nisi at augue blandit vulputate. Sed fringilla, enim ut aliquam interdum, eros sem ullamcorper nunc, vel rutrum diam diam sed tortor. Duis convallis risus massa, vitae malesuada metus malesuada at.', 3, 2, 3, 'read', null, 1716672272, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (17, 'user notif to close convers', 'sfjsljdfñsjdfñsdfsñdjfsjdfsñjdfñskjdfñlksjdfkñdjlfjñsdlkjfñsjdfñsjfñsjfñilsjdfñilsj fsiñdjf ñsjf ñoisdjfoñisjdfoñisjdfoiñsjdfo ijsdiofñ jsdñoif jsdoiñfj siodf jsdoñf ijsfdoñi jfsdoiñdfjñsodjfños', 3, 3, 2, 'replied', 18, 1716674708, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (18, 'a', '', 1, 2, 3, 'read', null, 1716675560, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (19, 'Aviso, me mudo', 'ñsadfhaif weñhfw w', 1, 3, 2, 'replied', 24, 1717169677, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (20, 'Ya he pagado la derrama del dia 7', 'ahfn  ia`dopqu  d9032 2j dsm2 d j', 2, 3, 2, 'replied', 23, 1717169700, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (21, 'Por favor arreglen la bombilla del pasillo', 'sdhfsdfñsndf jafj weoi ifj wioe fio  fiowf jwe', 3, 3, 2, 'unread', null, 1717169732, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (22, 'el sexto aviso', '6', 1, 3, 2, 'unread', null, 1717169748, 1717705515, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (23, 'mu bien, apuntado queda', 'asjfajsadñdajsd', 2, 2, 3, 'read', null, 1717170825, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (24, 'Debe usted rellenar el formulario p5', 'puede pedirlo en la oficina o en nuestra web www.form.com/p5', 2, 2, 3, 'replied', 25, 1717170872, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (25, 'pdf', 'puedo descargar el pdf e imprimirlo?', 2, 3, 2, 'replied', 26, 1717174492, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (26, 'instrucciones', 'Se trata de un pdf autorellenable. Puede editar los campos, guardarlo y enviarnoslo, o imprimirlo tras rellenarlo.
Si tiene alguna duda contacte con nosotros por teléfono.', 2, 2, 3, 'replied', 27, 1717174597, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (27, 'horario de oficina', 'me podria decir a que hora puedo llamarles?', 3, 3, 2, 'replied', 28, 1717174633, null, 3);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (28, 're: horario', 'nuestros horarios de oficina son de 8 a 2 y de 6 a 9', 2, 2, 3, 'read', null, 1717174683, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (29, 'hola', 'hola', 2, 8, 2, 'read', null, 1717175390, null, 8);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (30, 'Bienvenido a la comunidad', 'Ya puede ponerse en contacto con nosotros con su nueva cuenta de adminFin. ¡Bienvenido!', 2, 2, 8, 'read', null, 1717175970, null, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (31, 'Bienvenido', 'Bienvenido Ramiro, nos agrada mucho tenerte con nosotros. Si necesitas algo, ya sabes mi número personal.
Un abrazo', 2, 6, 7, 'read', null, 1717176053, null, 6);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (32, 'prueba update', 'prueba', 1, 2, 7, 'replied', 33, 1717534035, 1717534168, 7);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (33, 'respuesta', 'una respuesta', 2, 7, 2, 'unread', null, 1717534168, 1717705721, 2);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (34, 'saludos', 'bla bla', 2, 8, 6, 'replied', 35, 1717534992, 1717535037, 6);
INSERT INTO adminfindb.notification (id, title, message, type, sender_id, receiver_id, status, response_id, created_at, updated_at, updated_by) VALUES (35, 'hola', 'hola', 2, 6, 8, 'read', null, 1717535037, 1717535080, 8);
